apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        tier: backend
    spec:
      containers:
      - name: sample-app
        image: himanshuchandan/sample-java-app:newtoo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
    tier: backend
spec:
  selector:
    app: sample-app
    tier: backend
  type: NodePort
  ports:
    - port: 8080
